<?php
/** @var \Vendor\Module\Block\ProductLoad\SearchCriteriaMethod $block */

$productId = 1;
$product = $block->getProductById($productId);
?>
<div class="using-searchcriteria get-product">
        <h2><?= $block->escapeHtml(__('SearchCriteria Method')) ?></h2>
        <?php if ($product): ?>
            <div class="product-details">
                <p><strong><?= $block->escapeHtml(__('ID')) ?>:</strong> <?= $block->escapeHtml($product->getId());?></p>
                <p><strong><?= $block->escapeHtml(__('Name')) ?>:</strong> <?= $block->escapeHtml($product->getName());?></p>
                <p><strong><?= $block->escapeHtml(__('SKU')) ?>:</strong> <?= $block->escapeHtml($product->getSku());?></p>
            </div>
        <?php endif; ?>
    </div>
</div>